.TH "r1b_im_t" 3 "Wed Jun 17 2020" "Version 0.0.1" "r1b" \" -*- nroff -*-
.ad l
.nh
.SH NAME
r1b_im_t \- datatype for a (1-channel grayscale or binary) image  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <r1b\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "float * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
datatype for a (1-channel grayscale or binary) image 
.SH "Field Documentation"
.PP 
.SS "float* data"
image data: row-major array of floats 
.SS "int h"
height 
.SS "int w"
width 
.br
 

.SH "Author"
.PP 
Generated automatically by Doxygen for r1b from the source code\&.
